const ItemsData = [
  {
    id: "1",
    Image: "/images/img-18.png",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "/images/model (4).jpg",
    bath: "2 Bathroom",
    bathImage: "/images/model (4).jpg",
  },
  {
    id: "2",
    Image: "/images/img-18.png",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "/images/model (4).jpg",
    bath: "2 Bathroom",
    bathImage: "/images/model (4).jpg",
  },
  {
    id: "3",
    Image: "/images/img-18.png",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "/images/model (4).jpg",
    bath: "2 Bathroom",
    bathImage: "/images/model (4).jpg",
  },
  {
    id: "4",
    Image: "/images/img-18.png",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "/images/model (4).jpg",
    bath: "2 Bathroom",
    bathImage: "/images/model (4).jpg",
  },
  {
    id: "5",
    Image: "/images/img-18.png",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "/images/model (4).jpg",
    bath: "2 Bathroom",
    bathImage: "/images/model (4).jpg",
  },
  {
    id: "6",
    Image: "/images/img-18.png",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "/images/model (4).jpg",
    bath: "2 Bathroom",
    bathImage: "/images/model (4).jpg",
  },

  //   {
  //     id: "2",
  //     Image: "./PropertyImages/r-architecture-2gDwlIim3Uw-unsplash.jpg",
  //     heading: "Comfortable Apartment in Palace",
  //     span: "Popular Properties",
  //     amount: "From $20K",
  //     size: "1200 Sqft",
  //     bed: "2 Bed",
  //     bedImage:  "/images/model (4).jpg",
  //     bath: "2 Bathroom",
  //     bathImage:  "/images/model (4).jpg",
  //   },
];
export default ItemsData;
